apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: deployment-backend
spec:
  selector:
    app: deployment-backend
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  type: ClusterIP
