apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: deployment-frontend
spec:
  selector:
    app: deployment-frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort