name: Pipeline
on: 
  push:
    branches:
    - main

env:
  GIT_COMMIT: ${{ github.sha }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-frontend:
    name: Build and publish frontend image 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: chmod +x ./ci/build-frontend.sh && ./ci/build-frontend.sh
  build-backend:
    name: Build and publish backend image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: chmod +x ./ci/build-backend.sh && ./ci/build-backend.sh