name: Pipeline
on: 
  push:
    branches:
    - main

env:
  GIT_COMMIT: ${{ github.sha }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-frontend:
    name: Build and publish frontend image 
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: chmod +x ./ci/build-frontend.sh && ./ci/build-frontend.sh
      - name: Publish docker frontend image
        run: chmod +x ./ci/docker-publish-frontend.sh && ./ci/docker-publish-frontend.sh

  build-backend:
    name: Build and publish backend image
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: chmod +x ./ci/build-backend.sh && ./ci/build-backend.sh
      - name: Publish docker backend image
        run: chmod +x ./ci/docker-publish-backend.sh && ./ci/docker-publish-backend.sh