name: PR-workflow
on: 
  pull_request:

jobs:
  Test-frontend:
    runs-on: ubuntu-latest
    container: golang:1.20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        working-directory: ./frontend
        run: go test

  Test-backend:
    runs-on: ubuntu-latest
    container: golang:1.20
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
      - name: Test
        working-directory: ./backend
        run: go test



